<script>
  import geojsonUrl from "../data/lsoa_scores.geojson?url";
  import { onMount, getContext } from "svelte";

  const { getMap } = getContext("map");
  const map = getMap();

  const source = "baseline";
  const layer = "baseline_layer";

  export let hoveredAreaScores;

  let scoreLayer = "overall";

  onMount(async () => {
    let pair = await loadBasecores();
    let geojsonData = pair[0];
    map.addSource(source, {
      type: "geojson",
      data: geojsonData,
    });
    setLayer();

    map.on("mousemove", layer, function (e) {
      if (e.features.length > 0) {
        hoveredAreaScores = e.features[0].properties;
      }
    });
    map.on("mouseleave", layer, function () {
      hoveredAreaScores = null;
    });
  });

  function setLayer() {
    if (map.getLayer(layer)) {
      map.removeLayer(layer);
    }
    if (scoreLayer != "hide") {
      map.addLayer({
        id: layer,
        source: source,
        type: "fill",
        paint: {
          "fill-color": [
            "interpolate",
            ["linear"],
            ["get", scoreLayer],
            10,
            "#67001f",
            20,
            "#b2182b",
            30,
            "#d6604d",
            40,
            "#f4a582",
            50,
            "#fddbc7",
            60,
            "#d1e5f0",
            70,
            "#92c5de",
            80,
            "#4393c3",
            90,
            "#2166ac",
            100,
            "#053061",
          ],
          "fill-outline-color": "rgba(0, 0, 0, 0.2)",
          "fill-opacity": 0.7,
        },
      });
    }
  }

  function scoreTypes() {
    let purposes = [
      "Business",
      "Education",
      "Shopping",
      "Visit_friends_at_private_home",
      "Entertain_public_activity",
    ];
    let modes = ["car", "walk", "cycling", "pt"];
    let all = ["hide", "overall"];

    for (let mode of modes) {
      all.push(`overall_${mode}`);
    }

    for (let purpose of purposes) {
      all.push(`overall_${purpose.toLowerCase()}`);
      for (let mode of modes) {
        all.push(`${purpose}_${mode}`);
      }
    }
    return all;
  }

  // Returns the baseline GeoJSON data and also a dictionary from LSOA ID to
  // geometry (to later display recalculated scores)
  async function loadBasecores() {
    const resp = await fetch(geojsonUrl);
    const geojson = await resp.json();

    // "Uncompress" the string properties
    // This mapping is generated by shrink_gj.py
    let mapping = {
      "0": "LSOA11CD",
      "1": "Education_car",
      "2": "Business_car",
      "3": "Shopping_car",
      "4": "Education_walk",
      "5": "Business_pt",
      "6": "Education_pt",
      "7": "Visit_friends_at_private_home_car",
      "8": "Entertain_public_activity_car",
      "9": "Business_walk",
      "10": "Shopping_walk",
      "11": "Business_cycling",
      "12": "Education_cycling",
      "13": "Shopping_pt",
      "14": "Entertain_public_activity_pt",
      "15": "Visit_friends_at_private_home_pt",
      "16": "Shopping_cycling",
      "17": "Entertain_public_activity_walk",
      "18": "Visit_friends_at_private_home_walk",
      "19": "Entertain_public_activity_cycling",
      "20": "Visit_friends_at_private_home_cycling",
      "21": "overall",
      "22": "overall_walk",
      "23": "overall_car",
      "24": "overall_cycling",
      "25": "overall_pt",
      "26": "overall_business",
      "27": "overall_education",
      "28": "overall_entertain",
      "29": "overall_shopping",
      "30": "overall_visit",
    };
    for (let feature of geojson.features) {
      let props = {};
      for (let [k, v] of Object.entries(feature.properties)) {
        props[mapping[k]] = v;
      }
      feature.properties = props;
    }

    // Make a copy of the geometry, keyed by LSOA ID
    let lsoaGeometry = {};
    for (let feature of geojson.features) {
      let id = feature.properties["LSOA11CD"];
      lsoaGeometry[id] = feature.geometry;
    }

    return [geojson, lsoaGeometry];
  }
</script>

<div>
  Show LSOA scores:
  <select bind:value={scoreLayer} on:change={setLayer}>
    {#each scoreTypes() as x}
      <option value={x}>{x}</option>
    {/each}
  </select>
</div>

<style>
  div {
    z-index: 1;
    position: absolute;
    bottom: 250px;
    right: 10px;
    background: white;
    padding: 10px;
  }

  select {
    font-size: 16px;
    padding: 4px 8px;
  }
</style>
